--
-- Initial Authentication Schema
-- Contains only customer and refresh_tokens tables for authentication
--

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: customer; Type: TABLE; Schema: public
--

CREATE TABLE public.customer (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    email character varying(255) NOT NULL,
    is_banned boolean NOT NULL,
    is_enabled boolean NOT NULL,
    lastname character varying(255),
    name character varying(255),
    password character varying(255) NOT NULL,
    resettoken character varying(255),
    resettokenexpiry timestamp(6) with time zone,
    role character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    created_by bigint,
    updated_by bigint,
    deleted_by bigint,
    CONSTRAINT customer_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'MASTER'::character varying])::text[])))
);

--
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: refresh_tokens; Type: TABLE; Schema: public
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone,
    expirydate timestamp(6) with time zone NOT NULL,
    token character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone,
    customer_id bigint NOT NULL
);

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: customer customer_pkey; Type: CONSTRAINT; Schema: public
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT customer_pkey PRIMARY KEY (id);

--
-- Name: customer ukdwk6cx0afu8bs9o4t536v1j5v; Type: CONSTRAINT; Schema: public
--

ALTER TABLE ONLY public.customer
    ADD CONSTRAINT ukdwk6cx0afu8bs9o4t536v1j5v UNIQUE (email);

--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);

--
-- Name: refresh_tokens fk638pt9uhowpcmd698oypxaiiv; Type: FK CONSTRAINT; Schema: public
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk638pt9uhowpcmd698oypxaiiv FOREIGN KEY (customer_id) REFERENCES public.customer(id) ON DELETE CASCADE;

--
-- Create indexes to optimize hierarchical queries on customer table
--

-- Index for queries by created_by (used to get users created by an ADMIN)
CREATE INDEX IF NOT EXISTS idx_customer_created_by ON public.customer(created_by);

-- Composite index for queries that filter by created_by and is_enabled
CREATE INDEX IF NOT EXISTS idx_customer_created_by_enabled ON public.customer(created_by, is_enabled);

-- Composite index for queries that filter by role and is_enabled
CREATE INDEX IF NOT EXISTS idx_customer_role_enabled ON public.customer(role, is_enabled);

-- Composite index for complex queries that include created_by, role and is_enabled
CREATE INDEX IF NOT EXISTS idx_customer_hierarchy ON public.customer(created_by, role, is_enabled);

--
-- Enable pgcrypto extension for password hashing
--
CREATE EXTENSION IF NOT EXISTS pgcrypto;

--
-- Insert default users for testing and initial setup
-- All passwords are: "4dm1n1straT0r123$"
--

-- MASTER user (highest authority)
INSERT INTO public.customer (id, name, lastname, email, password, role, is_enabled, is_banned, created_at, updated_at) 
VALUES (
    1,
    'David',
    'García',
    'david@davscode.com',
    crypt('4dm1n1straT0r123$', gen_salt('bf')),
    'MASTER',
    true,
    false,
    NOW(),
    NOW()
);

-- ADMIN users (middle authority)
INSERT INTO public.customer (id, name, lastname, email, password, role, is_enabled, is_banned, created_at, updated_at) 
VALUES (
    2,
    'Denisse',
    'Rosado',
    'denisse@davscode.com',
    crypt('4dm1n1straT0r123$', gen_salt('bf')),
    'ADMIN',
    true,
    false,
    NOW(),
    NOW()
);

INSERT INTO public.customer (id, name, lastname, email, password, role, is_enabled, is_banned, created_at, updated_at) 
VALUES (
    3,
    'Moises',
    'Reyes',
    'moises@davscode.com',
    crypt('4dm1n1straT0r123$', gen_salt('bf')),
    'ADMIN',
    true,
    false,
    NOW(),
    NOW()
);

-- Regular USER accounts
INSERT INTO public.customer (id, name, lastname, email, password, role, is_enabled, is_banned, created_at, updated_at, created_by) 
VALUES (
    4,
    'Carlos',
    'Garcia',
    'carlos.garcia@davscode.com',
    crypt('4dm1n1straT0r123$', gen_salt('bf')),
    'USER',
    true,
    false,
    NOW(),
    NOW(),
    2 -- Created by Denisse (ADMIN)
);

INSERT INTO public.customer (id, name, lastname, email, password, role, is_enabled, is_banned, created_at, updated_at, created_by) 
VALUES (
    5,
    'Ana',
    'Martinez',
    'ana.martinez@davscode.com',
    crypt('4dm1n1straT0r123$', gen_salt('bf')),
    'USER',
    true,
    false,
    NOW(),
    NOW(),
    2 -- Created by Denisse (ADMIN)
);

-- Set sequence to continue from next value
SELECT setval('public.customer_id_seq', 5, true);

