--
-- RBAC Schema: permissions, roles, role_permissions
-- Migrates from enum-based role to dynamic RBAC
--

-- Permission table
CREATE TABLE public.permission (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description character varying(255),
    created_at timestamp(6) with time zone DEFAULT NOW(),
    CONSTRAINT permission_pkey PRIMARY KEY (id),
    CONSTRAINT permission_name_unique UNIQUE (name)
);

ALTER TABLE public.permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Role table (app_role to avoid PostgreSQL reserved word)

CREATE TABLE public.app_role (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(255),
    created_at timestamp(6) with time zone DEFAULT NOW(),
    CONSTRAINT app_role_pkey PRIMARY KEY (id),
    CONSTRAINT app_role_name_unique UNIQUE (name)
);

ALTER TABLE public.app_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Role-Permission many-to-many
CREATE TABLE public.role_permission (
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    CONSTRAINT role_permission_pkey PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES public.app_role(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES public.permission(id) ON DELETE CASCADE
);

-- Index for permission lookups in role_permission
CREATE INDEX IF NOT EXISTS idx_role_permission_permission_id ON public.role_permission(permission_id);

-- Add role_id to customer (nullable for migration)
ALTER TABLE public.customer ADD COLUMN role_id bigint;

-- Insert default permissions (aligned with SystemPermissions)
INSERT INTO public.permission (name, description) VALUES
    ('users', 'Manage users (create, read, update, delete)'),
    ('rbac', 'Manage roles and permissions'),
    ('admin', 'Full administrative access'),
    ('audit', 'View audit logs and system information');

-- Insert default roles
INSERT INTO public.app_role (name, description) VALUES
    ('USER', 'Standard user with basic access'),
    ('ADMIN', 'Administrator with user management'),
    ('MASTER', 'Master administrator with full access');

-- Assign permissions to roles
-- USER: no permissions (basic authenticated access)
-- ADMIN: users
INSERT INTO public.role_permission (role_id, permission_id)
SELECT r.id, p.id FROM public.app_role r, public.permission p
WHERE r.name = 'ADMIN' AND p.name = 'users';

-- MASTER: users, rbac, admin, audit
INSERT INTO public.role_permission (role_id, permission_id)
SELECT r.id, p.id FROM public.app_role r, public.permission p
WHERE r.name = 'MASTER' AND p.name IN ('users', 'rbac', 'admin', 'audit');

-- Migrate existing customer.role to role_id
-- Validate that all customer roles exist in app_role before migration
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM public.customer c
        WHERE NOT EXISTS (SELECT 1 FROM public.app_role r WHERE r.name = c.role)
    ) THEN
        RAISE EXCEPTION 'Migration validation failed: Some customer roles do not exist in app_role table';
    END IF;
END $$;

UPDATE public.customer c
SET role_id = (SELECT id FROM public.app_role r WHERE r.name = c.role);

-- Make role_id NOT NULL and add FK
ALTER TABLE public.customer ALTER COLUMN role_id SET NOT NULL;
ALTER TABLE public.customer ADD CONSTRAINT fk_customer_role FOREIGN KEY (role_id) REFERENCES public.app_role(id);

-- Drop old role column and constraint
ALTER TABLE public.customer DROP CONSTRAINT IF EXISTS customer_role_check;
ALTER TABLE public.customer DROP COLUMN role;

-- Index for role_id lookups
CREATE INDEX IF NOT EXISTS idx_customer_role_id ON public.customer(role_id);
